---
dataset:
  data_path: "/path/to/data/"
  annotation_path: "/path/to/annotation.json"
  height: 128
  width: 128
  win_size: 16
  stride: 2
  quick_run: false

model:
  model_path: "/path/to/code/"
  name: "cnn3d"
  model_parameters:
    input_channels: 1
    output_channels: 1
    final_layer: Sigmoid
  final_layer: Sigmoid
  device: cuda
  seed: 42

optimizer:
  name: Adam
  optimizer_parameters:
    lr: 1.0e-05
    weight_decay: 0.0

scheduler:
  use_scheduler: false
  name: ReduceLROnPlateau
  scheduler_parameters:
    mode: min
    factor: 0.1
    patience: 10

loss:
  name: AsymmetricUnifiedFocalLoss
  loss_parameters:
    weight: 0.5
    delta: 0.6
    gamma: 0.5

train:
  batch_size: 4
  num_workers: 2
  epochs: 150
  include_potential: true
  include_potential_gt: true
  data_parallel: true
  shuffle: true
  binary_gt: true
  threshold_iou: 0.9
  cross_validation:
    use_cross_validation: true
    fold_file: "/path/to/folds_dictionary.npy"
    fold_definition:
      train:
        - fold_1
        - fold_2
        - fold_3
        - fold_4
        - fold_5
        - fold_6
        - fold_7
        - fold_8
      test:
        - fold_9
      val:
        - fold_10
        
  data_augmentation:
  - name: ToTensor
  - name: RandomHorizontalFlip
    p: 0.5
  - name: RandomVerticalFlip
    p: 0.5
  load_checkpoint:
    load_model: False
    load_optimizer: False
    checkpoint_path: "/path/to/checkpoint.pth"
    updated_lr: 1.0e-05

evaluate:
  include_potential: true
  include_potential_gt: true
  shuffle: false
  binary_gt: true

test:
  model_path: "/path/to/model.pth"
  include_potential: true
  include_potential_gt: true
  shuffle: false
  binary_gt: true
  threshold_iou: 0.9